name: Build Layer ZIP

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Variables
        id: vars
        run: |
          sharp_version="0.33.5"
          echo "sharp_version=$sharp_version" >> $GITHUB_OUTPUT

          release_exists="true"
          git show-ref --tags --quiet --verify -- "refs/tags/$sharp_version" || release_exists="false"
          echo "release_exists=$release_exists" >> $GITHUB_OUTPUT
      - name: Build
        run: npm install --arch=x64 --platform=linux
      - name: Create release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.vars.outputs.sharp_version }}
          file: dist/sharp-layer.zip
          overwrite: true
